apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: classroom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: classroom
  template:
    metadata:
      labels:
        app: classroom
    spec:
      containers:
      - name: classroom
        image: classroom
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        envFrom:
          - configMapRef:
              name: kube-cluster-metadata