inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  CacheRootDirectory: ./tmp
  # https://github.com/thoughtbot/factory_bot/issues/1160#issuecomment-421410237
  RSpec:
    Patterns:
      - _test.rb
      - "(?:^|/)test/"
  RSpec/FactoryBot:
    Patterns:
      - test/factories/**/*.rb
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'vendor/**/.*'
    - 'node_modules/**/*'

Rails:
  Enabled: true

Layout/TrailingBlankLines:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/*.rb'

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_auth_hash

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Brewfile'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
