apiVersion: v1
kind: Service
metadata:
  name: classroom
  labels:
    service: classroom
  annotations:
    moda.github.net/domain-name: "classroom-%environment%.service.cp1-iad.github.net"
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: classroom
  type: LoadBalancer
