# For information on Sidekiq queues:
# https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues

---
:concurrency: <%= Integer(ENV['SIDEKIQ_CONCURRENCY'] || 5) %>
:verbose: false
:queues: # https://github.com/mperham/sidekiq/wiki/Advanced-Options#queues
  - [critical, 3]
  - [default,  2]
  - [low,      1]
